### ISSUE TITLE
Separate example and library

### ISSUE THREAD

**Issue by Lexikos** [TheArkive/scintilla_ahk2#2]
I would suggest separating the library from the example, so the library can be *#include*d in scripts directly. As it is, I would need to modify the file or extract the library if I wanted to use it in a script, and this creates unnecessary inconvenience if the library is ever updated.

I don't really want to read the library code itself, so I started by looking for an example that I could adapt to test it out. `test-script.ahk` seemed fairly obvious, so I was confused when I found that it was an unrelated v1 script and numerous libraries were missing. After opening the issue, I realized it's probably a sample file for the highlighter. Then I opened `scint5.ahk` and found the example and class, so I edited this issue.

**Comment by Lexikos** [comment]
Of course, immediately after opening the issue I realized it could be intended as a test for the highlighter, not an example library.

**Comment by TheArkive** [comment]
Gotcha.  Yah, this one did get a little messy.  I'll clean it up so it's easier to navigate.

**Comment by TheArkive** [comment]
Example now separate from main lib.  Any other suggestions / preferences for this cleanup?
