### ISSUE TITLE
Adding ScintillaControl.value

### ISSUE THREAD

**Issue by dmtr99** [TheArkive/scintilla_ahk2#6]
Is it possible to also add the value property to the scintilla control?

The standard text control of an edit control handles the linefeed and returns diffently.

**Comment by dmtr99** [comment]
This would make it easier to quickly exchange an edit control for a scintilla control

**Comment by TheArkive** [comment]
I don't see why not... I'll have to look it over to make sure I don't miss anything by making the change.  Lots of internal workings to double check.  But that should work fine.

**Comment by dmtr99** [comment]
Thanks, and by the way, great work, very usefull!

**Comment by TheArkive** [comment]
Complete
